### ISSUE TITLE
crash at start (Silicon macOS CODESIGNING)

### ISSUE THREAD

**Issue by Philk0033** [ctlcltd/e2-sat-editor#25]
### Describe the bug

Translated Report (Full Report Below)
-------------------------------------

[...]

Date/Time:             2024-07-21 20:33:13.9422 +0200
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        [...]

Sleep/Wake UUID:       [...]

Time Awake Since Boot: 1300000 seconds
Time Since Wake:       277408 seconds

System Integrity Protection: enabled

Crashed Thread:        0

**Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))**
Exception Codes:       UNKNOWN_0x32 at 0x0000000103268000
Exception Codes:       0x0000000000000032, 0x0000000103268000

**Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page**

[...]

### Steps to reproduce

1. 
2. 
3. 
...

### Software version

1.5

### Download medium

GitHub Releases page

### Platform running

macOS Sonoma

### Architecture running

arm64 (aarch64)

### Log

[...]

**Comment by ctlcltd** [comment]
This crash seems to be due to the lack of signature of the software on macOS with Silicon machine.

**This software is not signed.**

```
Code Type: ARM-64 (Native)
OS Version: macOS 14.5 (23F79)
Exception Type: EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Termination Reason: Namespace CODESIGNING, Code 2 Invalid Page
```

_Sorry, I had to edit your issue report for readability reason._

It seems they have added additional limitations to the OS using brand new Silicon chipset and macOS Sonoma, preventing software from unidentified developers from running. I cannot be sure, I do not have a mac with Silicon chipset.

Apple documentation page "Open a Mac app from an unidentified developer" explains how to open the software: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/

Signing the software would not be enough as, I don not have a Silicon mac.

I do not know if the intel build runs on Rosetta 2, same reason above.

If I have donations I could invest in software signature and testing on a cloud machine. The donations amount is 0.

Unfortunately, no software signing is currently planned.

This software is free software provided "AS IS".

**Comment by Philk0033** [comment]
Thank you.

**Comment by ctlcltd** [comment]
Thank you too, any help is precious.

Another solution could be to self-sign the released software, but **I do not know if it will work**. It requires knowledge of code signing software and membership in the Apple Developer Program with related terms and costs.

Sorry, this is the situation at the moment for macOS on Silicon mac.
