### ISSUE TITLE
login problem (connection profiles bug)

### ISSUE THREAD

**Issue by EnoSat** [ctlcltd/e2-sat-editor#27]
### Describe the bug

Create new profile. After connect show error - Missing username
![capture_002_27072024_124201](https://github.com/user-attachments/assets/f5f7519e-8978-4255-b896-fe9873e39988)
![capture_001_27072024_124150](https://github.com/user-attachments/assets/eb5f86c1-cf8a-4d0c-bd5e-c51b50bf7791)

### Steps to reproduce

1. 
2. 
3. 
...

### Software version

1.6

### Download medium

GitHub Releases page

### Platform running

Windows 11

### Architecture running

x86_64 (64-bit)

**Comment by ctlcltd** [comment]
Yes there is a bug, sorry for the inconvenience.

It occurs when you delete the "Default" profile (profile n. 1)

It will be fixed in next releases.

Temporarily you can get around it like this:
- Settings (Preferences)
- Export Profile (right click on profile or click "three dots menu" side bottom right corner)
- click on tab: "Advanced"
- set `profile.size` to `1`
- click outside the cell
- click on Save button
- again: Settings (Preferences)
- Import Profile
- click on Save button

Alternatively you can edit the file `e2 SAT Editor Team/e2se.ini`
- Open the INI file in a text editor
- rename all the entries `profile/2/PREFERENCE` to `profile/1/PREFERENCE`
- set `profile/selected` to `0`
- set `profile/size` to `1`

Last alternative, the worst, reset the preferences and then do not delete the Default profile (number 1), using and renaming it.
- Export Profile - steps above

Reset preferences:

- Settings (Preferences)
- click on tab: "Advanced"
- set `settings.reset` to `true`
- click outside the cell
- click on Save button
- close then re-open the software

Finally:
- Settings (Preferences)
- Import profile, or use the Default (profile n. 1) as your profile, renaming it

**Comment by ctlcltd** [comment]
Fixed with commit https://github.com/ctlcltd/e2-sat-editor/commit/a5b6551eb4df113d377d5b341f97523be4b8bade
This problem will be solved effective on next release.
